DROP TABLE IF EXISTS Schedule CASCADE;
DROP TABLE IF EXISTS Cruise CASCADE;
DROP TABLE IF EXISTS Captain CASCADE;
DROP TABLE IF EXISTS Ship CASCADE;
DROP TABLE IF EXISTS Reservation CASCADE;
DROP TABLE IF EXISTS Crew CASCADE;
DROP TABLE IF EXISTS Technician CASCADE;
DROP TABLE IF EXISTS Customer CASCADE;
DROP TABLE IF EXISTS Waitlist CASCADE;
DROP TABLE IF EXISTS Confirmed CASCADE;
DROP TABLE IF EXISTS Reserved CASCADE;
DROP TABLE IF EXISTS request CASCADE;

CREATE TABLE Schedule(cnum INT NOT NULL, day CHAR[10], depart_time CHAR[10], arrive_time CHAR[10], 
PRIMARY KEY (cnum), 
FOREIGN KEY(cnum) REFERENCES Cruise(cnum) ON DELETE CASCADE);

CREATE TABLE Captain(ID INT NOT NULL, name CHAR[10], 
PRIMARY KEY (ID));

CREATE TABLE Ship(model CHAR[10] NOT NULL, ID INT NOT NULL, make CHAR[10] NOT NULL, 
age INT NOT NULL, Seats INT NOT NULL, 
PRIMARY KEY (ID)); 

CREATE TABLE Reservation(Rnum INT NOT NULL, PRIMARY KEY (Rnum));

CREATE TABLE Customer(first_name CHAR[10], last_name CHAR[10], gender CHAR[10], date_of_birth CHAR[10] NOT NULL, 
address CHAR[64] NOT NULL, contact_num INT NOT NULL, ID INT NOT NULL, Zip_code INT NOT NULL,cnum INT NOT NULL, 
PRIMARY KEY (ID), 
FOREIGN KEY(cnum) REFERENCES Cruise(cnum) ON DELETE CASCADE);





